name: Windows_CI
on:
  workflow_dispatch:

  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  Onnxruntime-TVM:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'
          architecture: 'x64'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
      - name: Install Windows 8.1 SDK
        run: |
          import subprocess
          import urllib.request
          urllib.request.urlretrieve("https://go.microsoft.com/fwlink/p/?LinkId=323507", "sdksetup.exe")
          subprocess.run(["sdksetup.exe", "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"], check=True, capture_output=True)
        shell: python      
      - name: 'Install LLVM-Dev'
        shell: pwsh
        run: |
          conda install llvmdev=12.0.0
          conda info
          conda list
      - name: 'Add LLVM-Dev binaries to the PATH'
        run: |
          echo "C:/Miniconda/Library/bin" >> $GITHUB_PATH
      - name: 'Setup TVM EP Python requirements'
        run: |
          python3 -m pip install -r ${{ github.workspace }}/tools/ci_build/github/linux/tvm/requirements.txt
      - name: 'Build and Test'
        run: |
          python3 ${{ github.workspace }}/tools/ci_build/build.py  --build_dir build --config Release  --build_shared_lib  --disable_contrib_ops  --disable_ml_ops  --parallel  --skip_tests --skip_onnx_tests
